<?xml version="1.0" encoding="utf-8"?><Database Name="WebApiMVC" Class="LinqSqlClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LOVE-TW\SQLEXPRESS01;Initial Catalog=WebApiMVC;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WebApiMVCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.newemp" Member="newemps">
    <Type Name="newemp">
      <Column Name="Empid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Empname" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>